### ISSUE TITLE
It doesn't have a proper Readme 

### ISSUE THREAD

**Issue by cleverhare** [hkirat/linkedin-bot#8]
Hi Harkirat, This doesn't contain a proper Readme file which is a must for Open source projects. So if possible can you please assign this task to me?

**Comment by x0samnan** [comment]
Hi, @cleverhare. The PR for this issue is already opened. A suggestion or a review would be rather helpful than opening a new PR. That would duplicate the issue.

**Comment by cleverhare** [comment]
Thank you so much for your suggestion brother, I will keep this in mind and when the PR gets merged I will definitely try to update it..

**Comment by cleverhare** [comment]
This issue is already been made and is being worked on it. so this issue is now closed
